# Generated by Django 3.0.4 on 2020-04-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='agents',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='homes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
