# Generated by Django 3.0.4 on 2020-04-09 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_auto_20200406_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagent',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='home',
            name='demand',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='home',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='home',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='session',
            name='agents',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='session',
            name='homes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(49)]),
        ),
        migrations.AlterField(
            model_name='session',
            name='warehouse_latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='session',
            name='warehouse_longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddConstraint(
            model_name='deliveryagent',
            constraint=models.UniqueConstraint(fields=('session', 'number'), name='unique_agent'),
        ),
        migrations.AddConstraint(
            model_name='home',
            constraint=models.UniqueConstraint(fields=('session', 'number'), name='unique_home'),
        ),
    ]
