# Generated by Django 3.0.4 on 2020-04-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0006_auto_20200409_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='delivery_date',
            field=models.DateField(help_text='Use MM/DD/YY format'),
        ),
    ]
